import Foundation

extension RegisteredApplicationDocumentation {
    static let slackEmoji = LauncherApplicationDocumentation(
        category: .productivity, overview: "Search the custom emoji in your own Slack workspace through an explicitly configured internal app.",
        sections: [
            DocumentationSection(id: "slack.emoji.1", title: "Set up your internal Slack app", blocks: [.paragraph("slack.emoji.1.0", "Create a dedicated internal app in your own Slack dashboard with only the emoji:read bot scope. Workspace approval may be required. Paste its bot access token in Workspaces and choose Check & Connect. Commandly verifies its workspace, bot identity, and exact granted scope before saving it."), .paragraph("slack.emoji.1.1", "No account, app, authorization, or token is created automatically. This is an internal-app setup, not a distributed OAuth sign-in flow. Rotating access tokens must be replaced when they expire.")]),
            DocumentationSection(id: "slack.emoji.2", title: "Search and copy", blocks: [.paragraph("slack.emoji.2.0", "Choose a workspace and Refresh Emoji. Opening the tool or typing sends no Slack request. Search matches custom names and resolved alias targets. Return copies :name: for use in that workspace; Command–Shift–C copies the original image. Save Image writes its original bytes, including GIF animation."), .paragraph("slack.emoji.2.1", "Unavailable or cyclic aliases stay visible with a reason. An alias whose target is absent from Slack's custom inventory may still work when its name is pasted into Slack. Up to 300 matching names are shown; narrow the search to find more. Exact names rank first.")]),
            DocumentationSection(id: "slack.emoji.3", title: "Privacy and limits", blocks: [.paragraph("slack.emoji.3.0", "Only Slack's identity and custom-emoji APIs are called. No messages, channels, user profiles, or files are read or changed. Search text, names, aliases, and preview data are not logged or persisted. The current inventory is released when you leave the tool."), .paragraph("slack.emoji.3.1", "Selected emoji images are fetched from validated Slack image addresses without the bot token or cookies. Responses, image dimensions, frame count, memory, and redirects are bounded. Reduce Motion shows a still preview. Copy or Save only content you are authorized to use."), .paragraph("slack.emoji.3.2", "Remove Connection deletes this Mac's saved credential without uninstalling or revoking the Slack app. Use Slack's own dashboard to manage that installation.")])
        ]
    )
}
